### ISSUE TITLE
IOOS DAC compatibility issues: time variable not being populated with attributes

### ISSUE THREAD

**Issue by jklymak** [c-proof/pyglider#125]
Most of the other variables in our netcdf files have attributes, but `time` does not, despite it having an entry in deployment.yml.  Should be easy to add a code block to fill the attributes into the time variable.

**Comment by hvdosser** [comment]
Made a pull request with a small change to slocum.py. The code to do this was already there, `time` was just losing it's attributes later on in the processing (the coordinate was getting overwritten).

**Comment by hvdosser** [comment]
The `calendar` attribute for `time`, which is equal to `gregorian` in the deployment.yml file, is getting overwritten by `proleptic_gregorian` somewhere in the processing. However, I'm searched all the scripts, and can't figure out where this is happening.

**Comment by jklymak** [comment]
Probably https://github.com/c-proof/pyglider/blob/7fb31932557bfe5a7ff142253ff73427432f94e7/pyglider/slocum.py#L928-L929 is changing to `proleptic_gregorian`. OTOH, that shouldn't really cause a problem with the GDAC given that it is synonymous with `Gregorian` for the modern era.
