### ISSUE TITLE
sea explorer time base fallbacks don't work with parquet 

### ISSUE THREAD

**Issue by jklymak** [c-proof/pyglider#135]
https://github.com/c-proof/pyglider/blob/67c6acdf2b37926758090c273caa971930ccd1a2/pyglider/seaexplorer.py#L323

These lines error out if timebase is not specified in the yaml.  I guess we could enforce timebase in the yaml, but this code should be fixed or removed.

**Comment by callumrollo** [comment]
resolved in #139
