### ISSUE TITLE
consistent time unit

### ISSUE THREAD

**Issue by clayton33** [c-proof/pyglider#179]
I've recently started to process a handful of our Sea Explorer missions and we (@dankelley and @richardsc) noticed that the unit for time varies between the `timeseries`, `profiles`, and `grid` netCDF files. Currently the units are the following from the associated function

| function | time unit |
| --------- | ---------- |
| `seaexplorer.raw_to_timeseries` | `milliseconds since 1970-01-01T00:00:00+00:00` |
| `ncprocess..extract_timeseries_profiles` | `seconds since 1970-01-01T00:00:00+00:00` |
| `ncprocess.make_gridfiles` | `nanoseconds since 1970-01-01T00:00:00+00:00` |

Perhaps they should all be `seconds since 1970-01-01T00:00:00+00:00` to follow recent changes made to the `ncprocess.extract_timeseries_profiles` ?

**Comment by jklymak** [comment]
Yes I agree. Sorry for the inconsistencies - I hadn't appreciated how important keeping these consistent was but it does screw up various processing if the units change so this should be standardized

**Comment by callumrollo** [comment]
Yes it makes sense to impose consistency in the time units in SeaExplorer processing. We currently do it as part of our post processing. I'll work on a PR next week to standardise on float64 seconds since 1970

**Comment by callumrollo** [comment]
There are some other improvements I'd like to make to the SeaExplorer processing now that there is a stable version 1 release of polars, so it's a good time for an overhaul
