### ISSUE TITLE
timeunits in nanoseconds

### ISSUE THREAD

**Issue by mackenziemeier86** [c-proof/pyglider#191]
We tried to generate netcdf files for the glider DAC, however they weren't ERDDAP compliant because timeunits were in nano seconds. Our output looks like: 
int64 time(time) ;
                time:source = "sci_m_present_time" ;
                time:long_name = "Time" ;
                time:standard_name = "time" ;
                time:axis = "T" ;
                time:observation_type = "measured" ;
                time:units = "nanoseconds since 1970-01-01T00:00:00+00:00" ;
                time:calendar = "gregorian" ;

and gives the following error when uploading to DAC: 

datasets.xml error on line #668208
While trying to load datasetID=we15-20231209T1801 (after 63 ms)
java.lang.RuntimeException: datasets.xml error on or before line #668208: ERROR in Calendar2.factorToGetSeconds: units="nanoseconds" is invalid.
at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:486)
at gov.noaa.pfel.erddap.LoadDatasets.run(LoadDatasets.java:364)
Caused by: java.lang.RuntimeException: ERROR in Calendar2.factorToGetSeconds: units="nanoseconds" is invalid.

is the time actually being recorded in nanoseconds? or is it just a matter of changing the definition of timeunits to "seconds" instead of "nanoseconds"?

Thanks for the help!

**Comment by jklymak** [comment]
This should be fixed in the development version of pyglider.  Can you give it a try?

**Comment by mackenziemeier86** [comment]
Thanks! That seemed to have fix the nanosecond issue

**Comment by jklymak** [comment]
Yes, and I've released a newer pyglider to both condo-forge and pypi, so hopefully this is fixed for folks installing by normal channels.  Sorry for the bother.
