### ISSUE TITLE
Use of glider_devices

### ISSUE THREAD

**Issue by callumrollo** [c-proof/pyglider#22]
Are the fields in glider_devices from the deployment yaml used anywhere? I couldn't find them being accessed by any of the scripts in gliderpy. These fields include sensor names, serial numbers and calibration information. Could be useful to include in netCDF metadata, but I don't know how that would be done. Could just append them to metadata?

**Comment by soerenthomsen** [comment]
@callumrollo just reading through this now. Feel free to also join the debate about OG1.0 in the OceanGliders Data Format repo
