### ISSUE TITLE
Slow processing of large datasets

### ISSUE THREAD

**Issue by callumrollo** [c-proof/pyglider#36]
There appears to be a performance bottleneck in raw_to_rawnc. In the docstring it is noted that this is slow for large datasets. As this function converts small files individually, it looks ideal for multiprocessing.

**Comment by callumrollo** [comment]
Update: I've recently been introduced to [polars](https://github.com/pola-rs/polars) which looks like it would be an ideal solution for this. It's parallel by default  and works effectively as a replacement for pandas. I'll work up a PR to use polars in place of pandas for the seaexplorer raw_to_rawnc step

**Comment by jklymak** [comment]
We also introduced a method to subsample the data to remove all the redundant data the Alseamars put out by default.  Not sure if that helps fix the problem.  Not to say we shouldn't also consider polars.
