### ISSUE TITLE
AROD oxygen data wrong

### ISSUE THREAD

**Issue by callumrollo** [c-proof/pyglider#42]
From @bastienqueste:

> Note that oxygen from the AROD is wrong as it assumes a salinity of 0 PSU. To get proper oxygen, calculate saturation from the bad oxygen concentration and solubility calculated with good temperature and 0 salinity.
> From that saturation (which is a useful one to plot), we can get good concentration using a solubility calculated with good tmeperature and salinity.
> This salinity related error is probably about ~15-30% of the value so it's not worth ignoring

Does this fall within the remit of pyglider? It's not calibration of correction, just reporting accurate vales. It would involve a recalculation though.

**Comment by jklymak** [comment]
I don't know much about O2.  However, I think pyglider should convert to as close-to-correct as possible...

**Comment by jklymak** [comment]
(so long as the processing steps are able to be backed out from raw files)

**Comment by bastienqueste** [comment]
Careful though - people can change the onboard settings on the sensor to specify their own salinity - which some people do.
You can't assume it's 0 onboard and there's no way to know.
What Alsemar need to do is start outputting engineering units.

**Comment by richardsc** [comment]
@bastienqueste agree about how confusing this can be. It took us a long time of asking Alseamar and JFE before we even figured out the details that you mentioned above.

I believe that the assumption of 0 salinity for the AROD is the default, so perhaps that would be a good thing for pyglider to assume but with a caution for the user that they should check the configuration of their sensor. There is no way to know from the glider data what it is without connecting to the AROD separately and using the sensor software.

Note that this is also potentially an issue with the Aanderra optode normally mounted on slocum gliders -- there is a default salinity assumed in the output O2 concentration that should be corrected following the same procedure (convert to saturation using the assumed salinity and then recalculate concentration using the actual salinity/temperature). I don't know what the default for Aanderra is, but I recall it might be more sensible (like 34?).

**Comment by bastienqueste** [comment]
Same issue for all optodes. Coda included.

Aanderaa defaults change based on location specified on order and when it was. We've had some with different settings when we used to order with seagliders.

I agree proceeding with a warning is a viable option.

In a couple iterations, most or all sensors will start producing their own .raw files like the legato has started doing. These should have all data columns.

**Comment by callumrollo** [comment]
Resolved in #43
