### ISSUE TITLE
1970s from glider reboots

### ISSUE THREAD

**Issue by callumrollo** [c-proof/pyglider#55]
If a seaexplorer reboots mid-mission, a few 1970 datestamps will be produced before it gets a timefix from the GPS. This can mess up processing down the line, particularly as xarray assumes monotonically increasing datetime index for several operations. 

It would make sense to fix this as far upstream as possible. A crude but simple fix could be to drop any lines with datestamps before 1971 at the raw to rawnc stage. Or should it be left until later?

**Comment by jklymak** [comment]
Can you have a mission where the GPS never connects in which case you may want to keep the bad times as a timedelta?  But I think if any times exceed 1971, then the pre 1971 times can be safely removed or back calculated.

**Comment by callumrollo** [comment]
That's a sensible check. I'll start work on a PR. If we do it at the merge_rawnc stage, we can check if there are any 1971+ dates in the mission before dealing with rogue 1970s
